distributable:
  url: https://github.com/cloudnative-pg/cloudnative-pg/archive/refs/tags/v{{version}}.tar.gz
  strip-components: 1

versions:
  github: cloudnative-pg/cloudnative-pg

provides:
  - bin/kubectl-cnpg

build:
  dependencies:
    go.dev: ^1.23
  script: |
    go mod download
    mkdir -p "{{ prefix }}"/bin
    go build -v -trimpath -ldflags="$LDFLAGS" -o $BUILDLOC ./cmd/kubectl-cnpg/main.go
  env:
    linux:
      LDFLAGS:
      - -buildmode=pie
    GOPROXY: https://proxy.golang.org,direct
    GOSUMDB: sum.golang.org
    GO111MODULE: on
    CGO_ENABLED: 0
    BUILDLOC: '{{prefix}}/bin/kubectl-cnpg'
    LDFLAGS:
      - -s
      - -w
      - -X github.com/cloudnative-pg/cloudnative-pg/pkg/versions.buildVersion={{ version }}

test:
  script:
    - kubectl-cnpg version | grep "Version:{{version}} "
